# Generated by Django 4.0.5 on 2022-06-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_useraccountdetails_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountdetails',
            name='rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
