# Generated by Django 4.0.5 on 2022-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_useraccountdetails_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinquery',
            name='mail_id',
            field=models.EmailField(max_length=254),
        ),
    ]
